### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by pr0j3ctx** [sunsettrack4/zattoo_tvh#1]
Hello.

The Login failed. I get this message every time i try to login.
With the same Mail and Pass I can login at the webiste within my browser.

Is there any Problem? Using the Scripts on Ubuntu 16.04

**Comment by sunsettrack4** [comment]
Hello pr0j3ctx,

could you please edit "ztvh.sh" file in line 287 and retry?
read -e -sp "password..: " password

https://github.com/sunsettrack4/zattoo_tvh/blob/7761f342c768640d7b6004a80b9c46368192ffb3/ztvh.sh#L287

I'm already working on an update.

**Comment by sunsettrack4** [comment]
Hello pr0j3ctx,

could you please edit "ztvh.sh" file in line 287 and retry?

https://github.com/sunsettrack4/zattoo_tvh/blob/7761f342c768640d7b6004a80b9c46368192ffb3/ztvh.sh#L287

Change it to:
`read -e -sp "password..: " password`

I'm already working on an update.

**Comment by pr0j3ctx** [comment]
I am using the latest master from for an hour.

It´s line 293
https://github.com/sunsettrack4/zattoo_tvh/blob/c3e10c36e6b38db0b0b36fb5fee78a1d8ec5788c/ztvh.sh#L293

**Comment by sunsettrack4** [comment]
Please comment out line 319 with "#" symbol. After starting the script with failed login, open the file ~/ztvh/user/userfile and check if your credentials were saved correctly.

https://github.com/sunsettrack4/zattoo_tvh/blob/master/ztvh.sh#L319

**Comment by pr0j3ctx** [comment]
Yes. It`s correct
login=my@mail.de
password=mypass  

After typing in my credentials the script go to an endless loop

**Comment by sunsettrack4** [comment]
You can remove the "#" symbol now. Please re-create that userfile and type in your credentials with an alternative file manager like nano or gedit. "login=" and "password=" must be included. Does it work then?

**Comment by pr0j3ctx** [comment]
I write this file with vi and nano.

Same issue

**Comment by sunsettrack4** [comment]
Okay, go back to "ztvh.sh" file, that might be the issue. Please change line 305 to:

`curl -i -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Accept: application/x-www-form-urlencoded" -v --cookie "$session" --data-urlencode "$(sed '2d' ~/ztvh/user/userfile)" --data-urlencode "$(sed '1d' ~/ztvh/user/userfile)" https://zattoo.com/zapi/v2/account/login > login.txt 2> /dev/null`

https://github.com/sunsettrack4/zattoo_tvh/blob/master/ztvh.sh#L305

**Comment by pr0j3ctx** [comment]
Thx, Now it works!

**Comment by sunsettrack4** [comment]
Fixed: https://github.com/sunsettrack4/zattoo_tvh/commit/ec79604104e99bbf87dce86f99f3a1413d38cdb7
