### ISSUE TITLE
working with more than one instance

### ISSUE THREAD

**Issue by niwi-hh** [sunsettrack4/zattoo_tvh#11]
I would like to use more than one instance of zattoo_tvh. The reason is that I would like to run one instance for the German version and one (behind a vpn) for the Swiss version. Currently this is difficult because zatoo_tvh is using a lot of hardcoded links to ~/ztvh. Two instances would mean two working directories because of different settings.

**Comment by sunsettrack4** [comment]
To use a second instance, you have to create a second environment for your setup.

I created a folder called "ztvh2" and copy/pasted the scripts into that folder, then I renamed all parts containing the original "ztvh" name as follows:

```
sed -i "s/ztvh/ztvh2/g" filename # just enter this command for all files
mv ztvh.sh ztvh2.sh
```

To use the German Zattoo version while Swiss OpenVPN is enabled, please edit the second line of ~/ztvh2/pipe.sh to set a hardcoded server link and restart the ztvh2 script (please take the German account for ztvh2):

`curl -i -s -X POST -H "Content-Type: application/x-www-form-urlencoded" -H "Accept: application/x-www-form-urlencoded" --cookie "$session" --data "stream_type=hls&https_watch_urls=True&timeshift=10800"  https://PROVIDER/zapi/watch/live/CID_CHANNEL | grep "{" | sed 's/.*"stream": {"url": "//g;s/", .*//g;' > work/chlink && PIPE=$(sed '/zahs/{s/https:/http:/g;s/zahs.tv.*/zahs.tv/g;s/zba[0-9]-[0-9]/fra3-2/g;s/\//\\\//g;}' work/chlink) && curl -s $(<work/chlink) | \`

Finally, you have to add the server link to the openvpn.conf file and restart the OpenVPN service:

`route fra3-2-hls-live.zahs.tv 255.255.255.255 net_gateway`

In this way, you can watch all available channels provided by Zattoo. :)
