### ISSUE TITLE
No login possible

### ISSUE THREAD

**Issue by kalle2000** [sunsettrack4/zattoo_tvh#7]
Has the URL changed?

https://zattoo.com/zapi/v2/account/login

internal_code | 1
message | "The path '/zapi/v2/account/login' was not found."
success | false
http_status | 404

**Comment by sunsettrack4** [comment]
The URL didn't change, please check if your password is written correctly into ~/ztvh/user/userfile. The login works fine using my accounts.

Please also check if you get a true response by running the login commands manually.

Information about the hardware/firmware (OS) is also required.

**Comment by sunsettrack4** [comment]
The commit 03876b59612d6f83784eccd1414591455c089315 should fix your issue, otherwise please reopen this issue or create a new one.
