### ISSUE TITLE
Finding cookies for 1und1.tv fails

### ISSUE THREAD

**Issue by SteveOswald** [sunsettrack4/zattoo_tvh#9]
Hi,

I'm trying to use the script with 1un1.tv, but it stops at the "Waiting for required cookie data" point.

I fixed it, by replacing the content of the "save_page.js" with the following content:

```
var webPage = require('webpage');
var page = webPage.create();

page.open('https://PROVIDER/login', function () {
  setTimeout(function() {
    var cookies = page.cookies;

    console.log('Listing cookies:');
    for(var i in cookies) {
      console.log(cookies[i].name + '=' + cookies[i].value);
    }

    phantom.exit();
  }, 5000);
});
```

I think, the problem is, that the cookies aren't instantly available after the page has loaded.

Best regards,
Steve

**Comment by sunsettrack4** [comment]
Hello SteveOswald,

thank you for testing my new script, your fix is now included in commit 4702cf0c42525be9b0812b88de4a7c8c9f34de2f.

Best regards
sunsettrack4
